imports:
  - { resource: ../parameters.yml }

doctrine:
    dbal:
        default_connection: default
        connections:
          default:
            driver:   "%database_driver%"
            host:     "%database_host%"
            port:     "%database_port%"
            dbname:   "%database_name%"
            user:     "%database_user%"
            password: "%database_password%"
            charset:  UTF8
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            CbrRatesBundle:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/CbrRatesBundle/Entity'
                prefix: 'CbrRatesBundle\Entity'
                alias: 'CbrRatesBundle'
