index:
    path: /rates
    controller: CbrRatesBundle\Controller\RatesController::index

#index:
#    host:     "{domain}"
#    resource: "@ShiptorRussiaBundle/Controller"
#    prefix:   /rates
#    type:     annotation
#    defaults:
#        domain: "%main_domain%"
#    requirements:
#        domain: "%main_domain%"
#    schemes:  ["%protocol%"]
